In [1]:
import numpy as np

In [2]:
%store -r X
%store -r y
%store -r X_test
%store -r y_test

# Xây dựng mô hình CNN

In [3]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Khởi tạo mô hình
model = keras.Sequential()

# Thêm lớp Convolutional Layer với 32 bộ lọc kích thước 5x5 và hàm kích hoạt ReLU
model.add(layers.Conv2D(32, (5, 5), activation='relu', input_shape=(20, 128, 1), padding='same'))

# Thêm lớp Convolutional Layer với 32 bộ lọc kích thước 5x5 và hàm kích hoạt ReLU
model.add(layers.Conv2D(32, (5,5), activation='relu', padding='same'))

# Thêm lớp Max Pooling 2D để giảm kích thước đầu vào đi 2 lần
model.add(layers.MaxPooling2D((2, 2)))

# Thêm lớp Dropout để giảm hiện tượng overfitting
model.add(layers.Dropout(0.5))

# Thêm lớp Convolutional Layer với 64 bộ lọc kích thước 3x3 và hàm kích hoạt ReLU
model.add(layers.Conv2D(64, (5, 5), activation='relu', padding='same'))

# Thêm lớp Convolutional Layer với 64 bộ lọc kích thước 3x3 và hàm kích hoạt ReLU
model.add(layers.Conv2D(64, (5, 5), activation='relu', padding='same'))

# Thêm lớp Max Pooling 2D để giảm kích thước đầu vào đi 2 lần
model.add(layers.MaxPooling2D((2, 2)))

# Thêm lớp Flatten để làm phẳng đầu ra của lớp trước khi đi vào các lớp fully connected
model.add(layers.Flatten())

# Thêm lớp fully connected (Dense Layer) với 64 units và hàm kích hoạt ReLU
model.add(layers.Dense(64, activation='relu'))

# Thêm lớp Dropout để giảm hiện tượng overfitting
model.add(layers.Dropout(0.5))

# Thêm lớp fully connected (Dense Layer) cuối cùng với số lớp đầu ra phụ thuộc vào bài toán của bạn
model.add(layers.Dense(5, activation='softmax'))

# In thông tin mô hình
model.summary()

# Biên dịch mô hình
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])





Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 20, 128, 32)       832       
                                                                 
 conv2d_1 (Conv2D)           (None, 20, 128, 32)       25632     
                                                                 
 max_pooling2d (MaxPooling2  (None, 10, 64, 32)        0         
 D)                                                              
                                                                 
 dropout (Dropout)           (None, 10, 64, 32)        0         
                                                                 
 conv2d_2 (Conv2D)           (None, 10, 64, 64)        51264     
                                                                 
 conv2d_3 (Conv2D)           (None, 10, 64, 64)        102464    
                                                     

In [4]:
model.fit(X, y, epochs=10, validation_data=(X, y))

Epoch 1/10


412/412 [==============================] - 80s 191ms/step - loss: 0.9411 - accuracy: 0.6244 - val_loss: 0.4162 - val_accuracy: 0.8532
Epoch 2/10
412/412 [==============================] - 70s 171ms/step - loss: 0.5348 - accuracy: 0.7895 - val_loss: 0.2891 - val_accuracy: 0.8821
Epoch 3/10
412/412 [==============================] - 70s 169ms/step - loss: 0.4596 - accuracy: 0.8149 - val_loss: 0.2668 - val_accuracy: 0.8915
Epoch 4/10
412/412 [==============================] - 69s 168ms/step - loss: 0.4221 - accuracy: 0.8297 - val_loss: 0.2276 - val_accuracy: 0.9119
Epoch 5/10
412/412 [==============================] - 69s 168ms/step - loss: 0.3905 - accuracy: 0.8423 - val_loss: 0.2349 - val_accuracy: 0.9152
Epoch 6/10
412/412 [==============================] - 69s 169ms/step - loss: 0.3623 - accuracy: 0.8588 - val_loss: 0.2178 - val_accuracy: 0.9156
Epoch 7/10
412/412 [==============================] - 69s 168ms/step - loss: 0.3508 - accuracy: 0.8637 - val_loss: 0.2006 - val_

In [6]:
# Đánh giá mô hình trên tập kiểm tra
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print("Độ chính xác trên tập kiểm tra:", test_accuracy)

# Dự đoán các nhãn trên tập kiểm tra
y_pred = model.predict(X_test)

# Chuyển đổi dự đoán thành nhãn dự đoán (lớp dự đoán)
y_pred_classes = np.argmax(y_pred, axis=1)

# Hiển thị ma trận nhầm lẫn
from sklearn.metrics import confusion_matrix, classification_report
confusion = confusion_matrix(y_test, y_pred_classes)
print("Ma trận nhầm lẫn:")
print(confusion)

# Hiển thị báo cáo phân loại
class_report = classification_report(y_test, y_pred_classes)
print("Báo cáo phân loại:")
print(class_report)


412/412 [==============================] - 17s 42ms/step - loss: 0.1932 - accuracy: 0.9344
Độ chính xác trên tập kiểm tra: 0.9343764185905457
412/412 [==============================] - 18s 44ms/step
Ma trận nhầm lẫn:
[[2842    0    0    0    0]
 [   6 1976    7    8   37]
 [   2   22 2578    1  205]
 [   0  360    9 1366    5]
 [   0   33  169    0 3540]]
Báo cáo phân loại:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2842
           1       0.83      0.97      0.89      2034
           2       0.93      0.92      0.93      2808
           3       0.99      0.79      0.88      1740
           4       0.93      0.95      0.94      3742

    accuracy                           0.93     13166
   macro avg       0.94      0.92      0.93     13166
weighted avg       0.94      0.93      0.93     13166

