In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Flatten, Reshape

In [2]:
%store -r X_Transfer
%store -r y_Transfer
%store -r X_Transfer_test
%store -r y_Transfer_test

In [3]:
# Xây dựng mô hình
model = Sequential()

# Layer Convolutional (CNN)
model.add(Conv1D(32, kernel_size=(5), activation='relu', input_shape=(20, 128), padding='same'))
model.add(MaxPooling1D(pool_size=(2)))

# Layer LSTM
model.add(LSTM(64, activation='relu'))

# Thêm lớp Flatten để làm phẳng đầu ra của lớp trước khi đi vào các lớp fully connected
model.add(Flatten())

# Thêm lớp fully connected (Dense Layer) với 64 units và hàm kích hoạt ReLU
model.add(Dense(32, activation='relu'))

# Lớp Dense (có thể thay đổi theo bài toán cụ thể)
model.add(Dense(4, activation='softmax'))

# In thông tin mô hình
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 20, 32)            20512     
                                                                 
 max_pooling1d (MaxPooling1  (None, 10, 32)            0         
 D)                                                              
                                                                 
 lstm (LSTM)                 (None, 64)                24832     
                                                                 
 flatten (Flatten)           (None, 64)                0         
                                                                 
 dense (Dense)               (None, 32)                2080      
                                                                 
 dense_1 (Dense)             (None, 4)                 132       
                                                        

In [4]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_Transfer, y_Transfer, epochs=10, batch_size=16)

Epoch 1/10
589/589 [==============================] - 6s 7ms/step - loss: 0.4351 - accuracy: 0.8367
Epoch 2/10
589/589 [==============================] - 5s 8ms/step - loss: 0.2299 - accuracy: 0.9176
Epoch 3/10
589/589 [==============================] - 4s 7ms/step - loss: 0.1980 - accuracy: 0.9279
Epoch 4/10
589/589 [==============================] - 4s 7ms/step - loss: 0.1983 - accuracy: 0.9292
Epoch 5/10
589/589 [==============================] - 4s 7ms/step - loss: 0.1611 - accuracy: 0.9390
Epoch 6/10
589/589 [==============================] - 4s 7ms/step - loss: 0.1534 - accuracy: 0.9407
Epoch 7/10
589/589 [==============================] - 4s 7ms/step - loss: 0.1360 - accuracy: 0.9467
Epoch 8/10
589/589 [==============================] - 4s 6ms/step - loss: 0.1152 - accuracy: 0.9544
Epoch 9/10
589/589 [==============================] - 4s 7ms/step - loss: 0.1230 - accuracy: 0.9550
Epoch 10/10
589/589 [==============================] - 4s 6ms/step - loss: 0.1015 - accuracy: 0.9623

In [5]:
# Đánh giá mô hình trên tập kiểm tra
test_loss, test_accuracy = model.evaluate(X_Transfer_test, y_Transfer_test)
print("Độ chính xác trên tập kiểm tra:", test_accuracy)

# Dự đoán các nhãn trên tập kiểm tra
y_pred = model.predict(X_Transfer_test)

# Chuyển đổi dự đoán thành nhãn dự đoán (lớp dự đoán)
y_pred_classes = np.argmax(y_pred, axis=1)

# Hiển thị ma trận nhầm lẫn
from sklearn.metrics import confusion_matrix, classification_report
confusion = confusion_matrix(y_Transfer_test, y_pred_classes)
print("Ma trận nhầm lẫn:")
print(confusion)

# Hiển thị báo cáo phân loại
class_report = classification_report(y_Transfer_test, y_pred_classes)
print("Báo cáo phân loại:")
print(class_report)

295/295 [==============================] - 2s 5ms/step - loss: 0.0768 - accuracy: 0.9676
Độ chính xác trên tập kiểm tra: 0.9676358103752136
295/295 [==============================] - 2s 5ms/step
Ma trận nhầm lẫn:
[[2842    0    0    0]
 [   0 2011   12   11]
 [   0   20 2787    1]
 [   0  253    8 1479]]
Báo cáo phân loại:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2842
           1       0.88      0.99      0.93      2034
           2       0.99      0.99      0.99      2808
           3       0.99      0.85      0.92      1740

    accuracy                           0.97      9424
   macro avg       0.97      0.96      0.96      9424
weighted avg       0.97      0.97      0.97      9424



In [7]:
CNN_LSTM_model = model
%store CNN_LSTM_model

Stored 'CNN_LSTM_model' (Sequential)
