# Import thư viện

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Flatten, Reshape

# Đọc các biến từ file 128.ipynb

In [2]:
%store -r X
%store -r y
%store -r X_test
%store -r y_test

# Xây dựng mô hình

In [3]:
# Xây dựng mô hình
model = Sequential()

# Layer Convolutional (CNN)
model.add(Conv1D(32, kernel_size=(5), activation='relu', input_shape=(20, 128), padding='same'))
model.add(MaxPooling1D(pool_size=(2)))

# Layer LSTM
model.add(LSTM(64, activation='relu'))

# Thêm lớp Flatten để làm phẳng đầu ra của lớp trước khi đi vào các lớp fully connected
model.add(Flatten())

# Thêm lớp fully connected (Dense Layer) với 64 units và hàm kích hoạt ReLU
model.add(Dense(32, activation='relu'))

# Lớp Dense (có thể thay đổi theo bài toán cụ thể)
model.add(Dense(5, activation='softmax'))

# In thông tin mô hình
model.summary()



Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 20, 32)            20512     
                                                                 
 max_pooling1d (MaxPooling1  (None, 10, 32)            0         
 D)                                                              
                                                                 
 lstm (LSTM)                 (None, 64)                24832     
                                                                 
 flatten (Flatten)           (None, 64)                0         
                                                                 
 dense (Dense)               (None, 32)                2080      
                                                                 
 dense_1 (Dense)             (None, 5)                 165       
                                                      

# Biên dịch và huấn luyện mô hình

In [4]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X, y, epochs=10, batch_size=16)


Epoch 1/10


823/823 [==============================] - 17s 14ms/step - loss: 0.6248 - accuracy: 0.7657
Epoch 2/10
823/823 [==============================] - 11s 13ms/step - loss: 0.3604 - accuracy: 0.8682
Epoch 3/10
823/823 [==============================] - 11s 13ms/step - loss: 0.2910 - accuracy: 0.8960
Epoch 4/10
823/823 [==============================] - 11s 13ms/step - loss: 0.2578 - accuracy: 0.9036
Epoch 5/10
823/823 [==============================] - 12s 15ms/step - loss: 0.2280 - accuracy: 0.9165
Epoch 6/10
823/823 [==============================] - 16s 20ms/step - loss: 0.2153 - accuracy: 0.9204
Epoch 7/10
823/823 [==============================] - 12s 15ms/step - loss: 0.2063 - accuracy: 0.9229
Epoch 8/10
823/823 [==============================] - 12s 15ms/step - loss: 0.1863 - accuracy: 0.9281
Epoch 9/10
823/823 [==============================] - 11s 13ms/step - loss: 0.1725 - accuracy: 0.9341
Epoch 10/10
823/823 [==============================] - 11s 13ms/step - loss: 0.

# Đánh giá mô hình

In [5]:
# Đánh giá mô hình trên tập kiểm tra
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print("Độ chính xác trên tập kiểm tra:", test_accuracy)

# Dự đoán các nhãn trên tập kiểm tra
y_pred = model.predict(X_test)

# Chuyển đổi dự đoán thành nhãn dự đoán (lớp dự đoán)
y_pred_classes = np.argmax(y_pred, axis=1)

# Hiển thị ma trận nhầm lẫn
from sklearn.metrics import confusion_matrix, classification_report
confusion = confusion_matrix(y_test, y_pred_classes)
print("Ma trận nhầm lẫn:")
print(confusion)

# Hiển thị báo cáo phân loại
class_report = classification_report(y_test, y_pred_classes)
print("Báo cáo phân loại:")
print(class_report)

412/412 [==============================] - 6s 13ms/step - loss: 0.1443 - accuracy: 0.9459
Độ chính xác trên tập kiểm tra: 0.9459213018417358
412/412 [==============================] - 5s 11ms/step
Ma trận nhầm lẫn:
[[2842    0    0    0    0]
 [   0 1997    6    2   29]
 [   0    9 2655    1  143]
 [   2  334    6 1391    7]
 [   0    3  170    0 3569]]
Báo cáo phân loại:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2842
           1       0.85      0.98      0.91      2034
           2       0.94      0.95      0.94      2808
           3       1.00      0.80      0.89      1740
           4       0.95      0.95      0.95      3742

    accuracy                           0.95     13166
   macro avg       0.95      0.94      0.94     13166
weighted avg       0.95      0.95      0.95     13166



In [6]:
CNN_LSTM = model
%store CNN_LSTM

Stored 'CNN_LSTM' (Sequential)
