# Kết quả khi dùng dữ liệu gốc để train model CNN2D 

In [1]:
import pandas as pd
import numpy as np

# Đường dẫn đến file feather cần đọc
file_path = 'D:/ProJ/data/GQUIC_train_512.feather'

# Đọc file feather
df = pd.read_feather(file_path)

In [2]:
# Chọn cột '0' đến '127' cho mỗi flow_id và chuyển thành một danh sách các ma trận
matrices = []
labels = []
for flow_id, group in df.groupby('flow_id'):
    matrix = group.loc[:, '0':'511'].values
    label = group['Label'].values[0] 
    matrices.append(matrix)
    labels.append(label)

# Chuyển danh sách ma trận thành mảng NumPy
X = np.array(matrices)
X_512 = X / 255
y_512 = np.array(labels)

In [3]:
# Đường dẫn đến file feather cần đọc
file_path_test = 'D:/ProJ/data/GQUIC_test_512.feather'

# Đọc file feather
df_test = pd.read_feather(file_path)

In [4]:
# Chọn cột '0' đến '127' cho mỗi flow_id và chuyển thành một danh sách các ma trận
matrices_test = []
labels_test = []
for flow_id, group in df.groupby('flow_id'):
    matrix = group.loc[:, '0':'511'].values
    label = group['Label'].values[0] 
    matrices_test.append(matrix)
    labels_test.append(label)

# Chuyển danh sách ma trận thành mảng NumPy
X_test = np.array(matrices_test)
X_test_512 = X_test / 255
y_test_512 = np.array(labels_test)

In [5]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Khởi tạo mô hình
model = keras.Sequential()

# Thêm lớp Convolutional Layer với 32 bộ lọc kích thước 5x5 và hàm kích hoạt ReLU
model.add(layers.Conv2D(32, (5, 5), activation='relu', input_shape=(20, 512, 1), padding='same'))

# Thêm lớp Convolutional Layer với 32 bộ lọc kích thước 5x5 và hàm kích hoạt ReLU
model.add(layers.Conv2D(32, (5,5), activation='relu', padding='same'))

# Thêm lớp Max Pooling 2D để giảm kích thước đầu vào đi 2 lần
model.add(layers.MaxPooling2D((2, 2)))

# Thêm lớp Dropout để giảm hiện tượng overfitting
model.add(layers.Dropout(0.5))

# Thêm lớp Convolutional Layer với 64 bộ lọc kích thước 3x3 và hàm kích hoạt ReLU
model.add(layers.Conv2D(64, (5, 5), activation='relu', padding='same'))

# Thêm lớp Convolutional Layer với 64 bộ lọc kích thước 3x3 và hàm kích hoạt ReLU
model.add(layers.Conv2D(64, (5, 5), activation='relu', padding='same'))

# Thêm lớp Max Pooling 2D để giảm kích thước đầu vào đi 2 lần
model.add(layers.MaxPooling2D((2, 2)))

# Thêm lớp Flatten để làm phẳng đầu ra của lớp trước khi đi vào các lớp fully connected
model.add(layers.Flatten())

# Thêm lớp fully connected (Dense Layer) với 64 units và hàm kích hoạt ReLU
model.add(layers.Dense(64, activation='relu'))

# Thêm lớp Dropout để giảm hiện tượng overfitting
model.add(layers.Dropout(0.5))

# Thêm lớp fully connected (Dense Layer) cuối cùng với số lớp đầu ra phụ thuộc vào bài toán của bạn
model.add(layers.Dense(5, activation='softmax'))

# In thông tin mô hình
model.summary()

# Biên dịch mô hình
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

D:\.anaconda\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 20, 512, 32)         │             832 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 20, 512, 32)         │          25,632 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 10, 256, 32)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 10, 256, 32)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 10, 256, 64)         │          51,264 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (None, 10, 256, 64)         │         102,464 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 5, 128, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 40960)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 64)                  │       2,621,504 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 5)                   │             325 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,802,021 (10.69 MB)

 Trainable params: 2,802,021 (10.69 MB)

 Non-trainable params: 0 (0.00 B)

In [6]:
model.fit(X_512, y_512, epochs=10, batch_size=16)

Epoch 1/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 471s 569ms/step - accuracy: 0.5618 - loss: 1.0697
Epoch 2/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 622s 756ms/step - accuracy: 0.7645 - loss: 0.6108
Epoch 3/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 532s 646ms/step - accuracy: 0.7970 - loss: 0.5098
Epoch 4/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 332s 403ms/step - accuracy: 0.8131 - loss: 0.4732
Epoch 5/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 340s 413ms/step - accuracy: 0.8327 - loss: 0.4225
Epoch 6/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 2830s 3s/step - accuracy: 0.8352 - loss: 0.4042
Epoch 7/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 278s 338ms/step - accuracy: 0.8366 - loss: 0.4007
Epoch 8/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 286s 348ms/step - accuracy: 0.8392 - loss: 0.3862
Epoch 9/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 283s 344ms/step - accuracy: 0.8514 - loss: 0.3615
Epoch 10/10
823/823 ━━━━━━━━━━━━━━━━━━━━ 286s 348ms/step - accuracy: 0.8602 - loss: 0.3509


In [7]:
import numpy as np
# Đánh giá mô hình trên tập kiểm tra
test_loss, test_accuracy = model.evaluate(X_test_512, y_test_512)
print("Độ chính xác trên tập kiểm tra:", test_accuracy)

# Dự đoán các nhãn trên tập kiểm tra
y_pred = model.predict(X_test_512)

# Chuyển đổi dự đoán thành nhãn dự đoán (lớp dự đoán)
y_pred_classes = np.argmax(y_pred, axis=1)

# Hiển thị ma trận nhầm lẫn
from sklearn.metrics import confusion_matrix, classification_report
confusion = confusion_matrix(y_test_512, y_pred_classes)
print("Ma trận nhầm lẫn:")
print(confusion)

# Hiển thị báo cáo phân loại
class_report = classification_report(y_test_512, y_pred_classes)
print("Báo cáo phân loại:")
print(class_report)

412/412 ━━━━━━━━━━━━━━━━━━━━ 62s 149ms/step - accuracy: 0.9390 - loss: 0.1800
Độ chính xác trên tập kiểm tra: 0.9312623143196106
412/412 ━━━━━━━━━━━━━━━━━━━━ 65s 157ms/step
Ma trận nhầm lẫn:
[[2842    0    0    0    0]
 [   0 1986    8    1   39]
 [   0    7 2615    0  186]
 [   2  376    6 1320   36]
 [   0   29  215    0 3498]]
Báo cáo phân loại:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2842
           1       0.83      0.98      0.90      2034
           2       0.92      0.93      0.93      2808
           3       1.00      0.76      0.86      1740
           4       0.93      0.93      0.93      3742

    accuracy                           0.93     13166
   macro avg       0.94      0.92      0.92     13166
weighted avg       0.94      0.93      0.93     13166

